### ISSUE TITLE
last Rev. Compile Error

### ISSUE THREAD

**Issue by cold-hr** [15peaces/15-3athena#13]
![image](https://cloud.githubusercontent.com/assets/13975637/24069689/59d8265a-0be0-11e7-8eaa-fbdab24d11b3.png)

**Comment by 15peaces** [comment]
need some more infos here:
-client-date you want to compile?
-compiler used?
-sql / txt-mode?
-any mods?

**Comment by cold-hr** [comment]
- client / 2012-04-10
- vc++ 2010
- sql mode

**Comment by 15peaces** [comment]
ok, was able to reproduce. I'll fix it asap. ^^

**Comment by 15peaces** [comment]
fixed in 79b3444.
