### ISSUE TITLE
Guild window not displaying member names and territory

### ISSUE THREAD

**Issue by Nocc2k22** [15peaces/15-3athena#15]
Guild window doesn't display guild member names, and territories.
Guild announcement shows everytime on respawn, I checked the tables and everything seems fine. 
Edit: Checked map/login/char server, no error displayed
![screenragnarok164](https://user-images.githubusercontent.com/128347699/227747547-3a3c18fe-f76d-4561-8e0b-af0935b18385.jpg)
![screenragnarok160](https://user-images.githubusercontent.com/128347699/227747529-9127a988-d62a-4bd7-9705-51b78375a74e.jpg)
![screenragnarok162](https://user-images.githubusercontent.com/128347699/227747540-f47a3cee-6c98-4176-a5db-0e4dc60d51dd.jpg)

**Comment by 15peaces** [comment]
Guild announcement shows everytime on respawn:
https://github.com/15peaces/15-3athena/blob/master/conf/battle/guild.conf#L109

The rest seems to be a packet issue... I'll check it ^^
