### ISSUE TITLE
Bug Sit Icon

### ISSUE THREAD

**Issue by cold-hr** [15peaces/15-3athena#3]
now sit.  after that command @ load 
but sit icon Not missing

**Comment by 15peaces** [comment]
this bug is allready known but it's only a visual bug.

will be fixed later. ^^

**Comment by cold-hr** [comment]
yes now i fix from rAthena

thank you for fix.

**Comment by cold-hr** [comment]
skill.c
int skill_sit (struct map_session_data *sd, int type)

add
    if( type ) {
        clif_status_load(&sd->bl,SI_SIT,1);
    } else {
        clif_status_load(&sd->bl,SI_SIT,0);
    }

thank to fix

**Comment by 15peaces** [comment]
thanks for this.
I'll add it in my next commit. ^^
