### ISSUE TITLE
npc shop no show slot item

### ISSUE THREAD

**Issue by cold-hr** [15peaces/15-3athena#6]
vk_town,26,74,5 shop    Hat 1   703,2202:-1,2204:-1

not show slot can you help

**Comment by 15peaces** [comment]
maybe a problem with your client?
(slotcounttable.txt for 2012 and < // iteminfo.lua for newer clients)

**Comment by cold-hr** [comment]
I try to

**Comment by cold-hr** [comment]
vk_town,26,74,5 cashshop Hat 1 703,2202:-1,2204:-1

But if I can see a slot item.

**Comment by 15peaces** [comment]
could reproduce it now... I'll try to fixed asap.

Edit:
-will be fixed in my next commit. ^^

**Comment by cold-hr** [comment]
thank
