### ISSUE TITLE
sorry i want you help my request

### ISSUE THREAD

**Issue by cold-hr** [15peaces/15-3athena#8]
ok, now I can do it, you delete my post request it

**Comment by 15peaces** [comment]
I don't get it... what exactly is the problem? ^^"

Some more infos would help ^^

**Comment by cold-hr** [comment]
hide sprite on alt +q

**Comment by 15peaces** [comment]
what client are you using?

**Comment by cold-hr** [comment]
2012-04-10

i want to hide sprite on alt+q

you can custom or edit for me :D

**Comment by cold-hr** [comment]
ok, now I can do it, you delete my post request it
