### ISSUE TITLE
request fix bugs bargi

### ISSUE THREAD

**Issue by cold-hr** [15peaces/15-3athena#9]
https://rathena.org/board/tracker/issue-5571-bragi-overlap-bragi/
have link form rA

https://rathena.org/board/tracker/issue-1595-bugs-in-a-poem-of-bragi-skill/
https://rathena.org/board/tracker/issue-1595-bugs-in-a-poem-of-bragi-skill/

**Comment by 15peaces** [comment]
Fix will be commited later. ^^

**Comment by cold-hr** [comment]
thank
